name: Next.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  jobs:
    build:
      runs-on: unbuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout#v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Web build
        run: yarn build